version: '2'
services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    depends_on:
      - db
    env_file: ./pass.env
  db:
    build:
      context: .
      dockerfile: DockerFilePostgres
    env_file: ./pass.env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
    driver: local