version: '2'
services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    command: ['python', '-W ignore::DeprecationWarning', 'manage.py', 'runserver', '0.0.0.0:800<&', '--settings=duck_site.duck_site.settings']
    depends_on:
      - db
    env_file: ./pass.env
  db:
    build:
      context: .
      dockerfile: DockerFilePostgres
    env_file: ./pass.env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
    driver: local